# Generated by Django 5.1.2 on 2024-10-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buspark',
            name='logo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
