# Generated by Django 4.2.16 on 2024-10-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bas', '0002_alter_buspark_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspark',
            name='year_found',
            field=models.IntegerField(null=True, verbose_name='Год основания'),
        ),
    ]
