# Generated by Django 4.2.16 on 2024-10-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bas', '0003_buspark_year_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buspark',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
