# Generated by Django 4.2.16 on 2024-10-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bas', '0004_alter_buspark_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspark',
            name='decription',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
