# Generated by Django 4.2.16 on 2024-10-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bas', '0005_buspark_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buspark',
            old_name='decription',
            new_name='description',
        ),
    ]
